spring.application.name=controlz

# Configuracion del origen de datos (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/controlz?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Cl3t41234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.mvc.format.date=yyyy-MM-dd

